//
//  Deck.swift
//  Better UNO
//
//  Created by Jesse Brior on 11/29/21.
//

import Foundation

struct Deck {
    let defaultDeck: [String:[String]] = [
        "RedCards": [
            "red-0-1",
            "red-1-1",
            "red-2-1",
            "red-3-1",
            "red-4-1",
            "red-5-1",
            "red-6-1",
            "red-7-1",
            "red-8-1",
            "red-9-1",
            "red-skip-1",
            "red-reverse-1",
            "red-draw-1",
            "red-0-2",
            "red-1-2",
            "red-2-2",
            "red-3-2",
            "red-4-2",
            "red-5-2",
            "red-6-2",
            "red-7-2",
            "red-8-2",
            "red-9-2",
            "red-skip-2",
            "red-reverse-2",
            "red-draw-2"
        ],
        "YellowCards": [
            "yellow-0-1",
            "yellow-1-1",
            "yellow-2-1",
            "yellow-3-1",
            "yellow-4-1",
            "yellow-5-1",
            "yellow-6-1",
            "yellow-7-1",
            "yellow-8-1",
            "yellow-9-1",
            "yellow-skip-1",
            "yellow-reverse-1",
            "yellow-draw-1",
            "yellow-0-2",
            "yellow-1-2",
            "yellow-2-2",
            "yellow-3-2",
            "yellow-4-2",
            "yellow-5-2",
            "yellow-6-2",
            "yellow-7-2",
            "yellow-8-2",
            "yellow-9-2",
            "yellow-skip-2",
            "yellow-reverse-2",
            "yellow-draw-2"
        ],
        "BlueCards": [
            "blue-0-1",
            "blue-1-1",
            "blue-2-1",
            "blue-3-1",
            "blue-4-1",
            "blue-5-1",
            "blue-6-1",
            "blue-7-1",
            "blue-8-1",
            "blue-9-1",
            "blue-skip-1",
            "blue-reverse-1",
            "blue-draw-1",
            "blue-0-2",
            "blue-1-2",
            "blue-2-2",
            "blue-3-2",
            "blue-4-2",
            "blue-5-2",
            "blue-6-2",
            "blue-7-2",
            "blue-8-2",
            "blue-9-2",
            "blue-skip-2",
            "blue-reverse-2",
            "blue-draw-2"
        ],
        "GreenCards": [
            "green-0-1",
            "green-1-1",
            "green-2-1",
            "green-3-1",
            "green-4-1",
            "green-5-1",
            "green-6-1",
            "green-7-1",
            "green-8-1",
            "green-9-1",
            "green-skip-1",
            "green-reverse-1",
            "green-draw-1",
            "green-0-2",
            "green-1-2",
            "green-2-2",
            "green-3-2",
            "green-4-2",
            "green-5-2",
            "green-6-2",
            "green-7-2",
            "green-8-2",
            "green-9-2",
            "green-skip-2",
            "green-reverse-2",
            "green-draw-2",
        ],
        "MiscCards": [
            "wild-1",
            "wild-2",
            "wild-3",
            "wild-4",
            "drawFour-1",
            "drawFour-2",
            "drawFour-3",
            "drawFour-4"
        ]
    ]
}
